name       : rubberband
version    : 1.8.1
release    : 1
source     :
    - http://code.breakfastquay.com/attachments/download/34/rubberband-1.8.1.tar.bz2 : ff0c63b0b5ce41f937a8a3bc560f27918c5fe0b90c6bc1cb70829b86ada82b75
license    : GPL-2.0
summary    : A high quality software library for audio time-stretching and pitch-shifting.
description: |
    A high quality software library for audio time-stretching and pitch-shifting.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vamp)
    - ladspa-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
