name       : rubberband
version    : '1.9'
release    : 3
source     :
    - https://github.com/breakfastquay/rubberband/archive/v1.9.tar.gz : 779e9a5e45f869618261b98b8d0c262fcbe066418a1c836fb85de47fbc1b29aa
license    : GPL-2.0-or-later
component  : programming.library
homepage   : https://breakfastquay.com/rubberband/
summary    : A high quality software library for audio time-stretching and pitch-shifting.
description: |
    A high quality software library for audio time-stretching and pitch-shifting.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vamp)
    - ladspa-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/lib/librubberband.a
