name       : rubberband
version    : 1.9.2
release    : 5
source     :
    - https://github.com/breakfastquay/rubberband/archive/refs/tags/v1.9.2.tar.gz : 2b8fc79314fa11048860be78e40b3463aa9dec474f69c0a1dd68c48c02600f6a
license    : GPL-2.0-or-later
component  : programming.library
homepage   : https://breakfastquay.com/rubberband/
summary    : A high quality software library for audio time-stretching and pitch-shifting.
description: |
    A high quality software library for audio time-stretching and pitch-shifting.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vamp)
    - ladspa-devel
setup      : |
    %meson_configure -Dfft=fftw --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/lib64/librubberband.a
