name       : rubberband
version    : 3.2.1
release    : 7
source     :
    - https://github.com/breakfastquay/rubberband/archive/refs/tags/v3.2.1.tar.gz : 05b4ff2856c4e65d235dda3b2370d3a025f4667dbdac72bc24c0175fce33639e
license    : GPL-2.0-or-later
component  : programming.library
homepage   : https://breakfastquay.com/rubberband/
summary    : A high quality software library for audio time-stretching and pitch-shifting.
description: |
    A high quality software library for audio time-stretching and pitch-shifting.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vamp)
    - ladspa-devel
setup      : |
    %meson_configure \
        -Dfft=fftw \
        -Dresampler=libsamplerate \
        --buildtype=release
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/lib64/librubberband.a
