name       : rubberband
version    : 1.8.2
release    : 2
source     :
    - https://github.com/breakfastquay/rubberband/archive/v1.8.2.tar.gz : 0bb058710b476712480cf6b3e1c1178c6237e9e8e3c98092f00e31632a011d15
license    : GPL-2.0-or-later
component  : programming.library
summary    : A high quality software library for audio time-stretching and pitch-shifting.
description: |
    A high quality software library for audio time-stretching and pitch-shifting.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vamp)
    - ladspa-devel
    - openjdk-8-devel
setup      : |
    %reconfigure
build      : |
    %make
    export JAVA_HOME=/usr/lib64/openjdk-8
    %make jni
install    : |
    %make_install
    rm $installdir/usr/lib/librubberband.a
    rm $installdir/usr/lib/librubberband-jni.so